require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

# Disable Flipper
ENV['NO_FLIPPER'] = '1'

target 'HyBidCalculator' do
  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )
  
  # HyBid SDK
  pod 'HyBid', '~> 2.4.3'
  
  target 'HyBidCalculatorTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
    
    # Set deployment target
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
